# https://rust-lang.github.io/rustfmt

# max_width = 100
# chain_width = 60

binop_separator = "Front"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
combine_control_expr = false
empty_item_single_line = true
fn_params_layout = "Tall"
fn_single_line = true
force_multiline_blocks = true
hard_tabs = false
hex_literal_case = "Lower"
imports_indent = "Block"
indent_style = "Block"
match_block_trailing_comma = true
merge_derives = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = true
struct_field_align_threshold = 20
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"

